backend:
  name: git-gateway
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["SEO", "AEO", "Growth", "Case Chronicles", "Reputation"] }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
